export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  message?: string;
  timestamp?: string;
  error?: string;
  errorCode?: string;
  statusCode?: number;
}

export interface PageResult<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export type ListResult<T> = PageResult<T> | T[];

export interface MessageResponse {
  message: string;
}

export enum Role {
  STUDENT = "STUDENT",
  LECTURER = "LECTURER",
  HOD = "HOD",
  COLLEGE_ADMIN = "COLLEGE_ADMIN",
  ADMIN = "ADMIN",
}

export enum Level {
  LEVEL_100 = "LEVEL_100",
  LEVEL_200 = "LEVEL_200",
  LEVEL_300 = "LEVEL_300",
  LEVEL_400 = "LEVEL_400",
  LEVEL_500 = "LEVEL_500",
}

export enum College {
  CBAS = "CBAS",
  CHMS = "CHMS",
  CAHS = "CAHS",
}

export enum Semester {
  FIRST = "FIRST",
  SECOND = "SECOND",
}

export enum DayOfWeek {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

export enum SessionType {
  THEORY = "THEORY",
  PRACTICAL = "PRACTICAL",
}

export enum ComplaintStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
}

export enum VenueType {
  UNIVERSITY_ICT_CENTER = "UNIVERSITY_ICT_CENTER",
  ICT_LAB_1 = "ICT_LAB_1",
  ICT_LAB_2 = "ICT_LAB_2",
  COMPUTER_LAB = "COMPUTER_LAB",
  LECTURE_HALL_1 = "LECTURE_HALL_1",
  LECTURE_HALL_2 = "LECTURE_HALL_2",
  LECTURE_HALL_3 = "LECTURE_HALL_3",
  AUDITORIUM_A = "AUDITORIUM_A",
  AUDITORIUM_B = "AUDITORIUM_B",
  SEMINAR_ROOM_A = "SEMINAR_ROOM_A",
  SEMINAR_ROOM_B = "SEMINAR_ROOM_B",
  ROOM_101 = "ROOM_101",
  ROOM_102 = "ROOM_102",
  ROOM_201 = "ROOM_201",
  ROOM_202 = "ROOM_202",
  ROOM_301 = "ROOM_301",
  ROOM_302 = "ROOM_302",
  SCIENCE_LAB_1 = "SCIENCE_LAB_1",
  SCIENCE_LAB_2 = "SCIENCE_LAB_2",
}

export const ICT_VENUES: VenueType[] = [
  VenueType.UNIVERSITY_ICT_CENTER,
  VenueType.ICT_LAB_1,
  VenueType.ICT_LAB_2,
  VenueType.COMPUTER_LAB,
];

export interface User {
  id: string;
  matricNO: string;
  email: string;
  name: string | null;
  role: Role;
  phone?: string | null;
  departmentCode?: string | null;
  collegeCode?: College | null;
  department?: Pick<Department, "name" | "code" | "college"> | null;
  isActive: boolean;
  lastLoginAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type Lecturer = User & {
  role: Role.LECTURER | Role.HOD;
  departmentCode: string;
};

export type CurrentUser = Omit<User, "isActive" | "department"> & {
  isActive?: boolean;
  department?: Pick<Department, "name" | "code"> | null;
};

export interface AuthUser extends Pick<User, "id" | "email" | "name" | "role"> {
  matricNO?: string;
  departmentCode?: string | null;
  collegeCode?: College | null;
  createdAt?: string;
}

export interface AuthResponse {
  user: AuthUser;
  access_token: string;
  token_type: string;
}
export interface Department {
  id: string;
  name: string;
  code: string;
  courses?: Course[];
  description?: string | null;
  college: College;
  hodId?: string | null;
  hod?: Pick<User, "id" | "name" | "email" | "role"> | null;
  isActive: boolean;
  isScheduleLocked: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Course {
  id: string;
  code: string;
  name: string;
  overview?: string | null;
  level: Level;
  credits: number;
  semester: Semester;
  aliasWarnings?: string[];
  departmentCode: string;
  department?: Department;
  lecturerId?: string | null;
  lecturer?: Pick<
    User,
    "id" | "name" | "email" | "phone" | "departmentCode"
  > | null;
  isGeneral: boolean;
  isLocked: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  schedules?: Schedule[];
  primaryAliases?: Array<{
    id: string;
    aliasCourse: { code: string; name: string; departmentCode: string };
  }>;
  aliasOf?: Array<{
    id: string;
    primaryCourse: { code: string; name: string; departmentCode: string };
  }>;
}

export interface CourseAlias {
  id: string;
  primaryCode: string;
  aliasCode: string;
  createdAt: string;
  primaryCourse?: {
    code: string;
    name: string;
    departmentCode: string;
    level?: Level;
  };
  aliasCourse?: {
    code: string;
    name: string;
    departmentCode: string;
    level?: Level;
  };
}

export interface AcademicSession {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface Schedule {
  id: string;
  courseCode: string;
  course?: Course;
  semester: Semester;
  sessionId: string;
  dayOfWeek: DayOfWeek;
  startTime: string;
  endTime: string;
  sessionType: SessionType;
  isAutoGenerated: boolean;
  isManualOverride: boolean;
  isFixed: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Exam {
  id: string;
  courseCode: string;
  course?: Course;
  date: string;
  startTime: string;
  endTime: string;
  venue: VenueType;
  studentCount: number;
  targetCollege?: College | null;
  invigilators?: string | null;
  semester: Semester;
  sessionId: string;
  createdAt: string;
  updatedAt: string;
}

export interface GenerateExamTimetableData {
  semester: Semester;
  sessionId?: string;
  departmentCode?: string;
  level?: Level;
  college?: College;
}

export interface GenerateExamTimetableResult {
  sessionId: string;
  sessionName: string;
  semester: Semester;
  departmentCode: string | null;
  level: Level | null;
  college: College | null;
  totalCourses: number;
  scheduledExams: number;
  skippedCourses: string[];
}

export interface Complaint {
  id: string;
  userId?: string | null;
  user?: Pick<User, "id" | "name" | "email"> | null;
  name: string;
  email: string;
  department: string;
  subject: string;
  message: string;
  status: ComplaintStatus;
  resolvedBy?: string | null;
  resolvedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ScheduleAssignment {
  courseCode: string;
  dayOfWeek: DayOfWeek;
  startTime: string;
  endTime: string;
  semester: Semester;
  sessionType?: SessionType;
}

export interface UnscheduledCourse {
  courseCode: string;
  courseName: string;
  departmentCode: string;
  level: Level;
  semester: Semester;
  reason: string;
}

export interface DepartmentSchedulingError {
  departmentCode: string;
  message: string;
}

export interface GenerateScheduleResult {
  sessionId: string;
  sessionName: string;
  semester: Semester;
  departmentCode: string | null;
  programme: string | null;
  level: Level | null;
  totalCourses: number;
  scheduledCount: number;
  failedCount: number;
  preservedOverrides: number;
  skippedLockedDepartments: number;
  scheduledCourses: ScheduleAssignment[];
  unscheduledCourses: UnscheduledCourse[];
  success: boolean;
}

export interface RecommendedSlot {
  courseCode: string;
  dayOfWeek: string;
  startTime: string;
  endTime: string;
  hasConflict: boolean;
}

export interface Programme {
  programme: string;
  count: number;
}

export interface SessionStatistics {
  totalSchedules: number;
  totalExams: number;
  schedulesBySemester: {
    FIRST: number;
    SECOND: number;
  };
  examsBySemester: {
    FIRST: number;
    SECOND: number;
  };
}

export interface ScheduleStatistics {
  totalSchedules: number;
  schedulesByDay: Record<DayOfWeek, number>;
  autoGenerated: number;
  manualOverrides: number;
}

export interface CourseStatistics {
  totalCourses: number;
  coursesByLevel: Record<Level, number>;
  coursesByDepartment: Record<string, number>;
  averageCredits: number;
}

export interface DepartmentStatistics {
  totalDepartments: number;
  departmentsWithCourses: number;
  departmentsWithoutCourses: number;
  averageCoursesPerDepartment: number;
}

export interface LecturerDashboard {
  totalCourses: number;
  totalSchedules: number;
  coursesByLevel: Record<string, number>;
  schedulesByDay: Record<string, number>;
  upcomingClasses: number;
}

export interface BulkOperationResult<T> {
  success: boolean;
  created: T[];
  errors: Array<{
    row: number;
    field: string;
    value: unknown;
    message: string;
  }>;
  aliasWarnings?: string[];
  summary: {
    totalRows: number;
    successCount: number;
    errorCount: number;
  };
}

export interface FileBulkResult<T> {
  fileName: string;
  result: BulkOperationResult<T>;
}

export interface MultiFileBulkOperationResult<T> {
  success: boolean;
  files: FileBulkResult<T>[];
  summary: {
    totalFiles: number;
    totalRows: number;
    successCount: number;
    errorCount: number;
  };
}

export interface LoginData {
  email: string;
  password: string;
}

export type SelfRegistrationRole = Role.STUDENT | Role.LECTURER;

export interface RegisterData {
  matricNO: string;
  email: string;
  password: string;
  name?: string;
  role?: SelfRegistrationRole;
  departmentCode: string;
  phone?: string;
}

export interface CreateDepartmentData {
  name: string;
  code: string;
  description?: string;
  college?: College;
  hodId?: string;
}

export interface UpdateDepartmentData extends Partial<CreateDepartmentData> {}

export interface CreateCourseData {
  code: string;
  name: string;
  overview?: string;
  level: Level;
  semester: Semester;
  credits: number;
  departmentCode: string;
  lecturerId?: string;
  isGeneral?: boolean;
  isLocked?: boolean;
  aliasOf?: string[];
}

export interface UpdateCourseData extends Partial<CreateCourseData> {}

export interface CreateScheduleData {
  courseCode: string;
  dayOfWeek: DayOfWeek;
  startTime: string;
  endTime: string;
  sessionType?: SessionType;
  isFixed?: boolean;
}

export interface UpdateScheduleData extends Partial<CreateScheduleData> {}

export interface GenerateScheduleData {
  semester: Semester;
  sessionId?: string;
  departmentCode?: string;
  level?: Level;
  programme?: string;
}

export interface BatchGenerateScheduleResult {
  sessionId: string;
  sessionName: string;
  semester: Semester;
  programme: string | null;
  totalDepartments: number;
  processedDepartments: number;
  skippedLockedDepartments: number;
  totalCourses: number;
  scheduledCount: number;
  failedCount: number;
  preservedOverrides: number;
  scheduledCourses: ScheduleAssignment[];
  unscheduledCourses: UnscheduledCourse[];
  errors: DepartmentSchedulingError[];
  success: boolean;
}

export interface CreateAcademicSessionData {
  name: string;
  startDate: string;
  endDate: string;
}

export interface UpdateAcademicSessionData {
  name?: string;
  startDate?: string;
  endDate?: string;
  isActive?: boolean;
}

export interface CreateExamData {
  courseCode: string;
  date: string;
  startTime: string;
  endTime: string;
  venue: VenueType;
  studentCount: number;
  invigilators?: string;
  targetCollege?: College;
}

export interface UpdateExamData extends Partial<CreateExamData> {}

export interface CreateComplaintData {
  name: string;
  email: string;
  department: string;
  subject: string;
  message: string;
}

export interface CreateUserData {
  matricNO: string;
  email: string;
  password: string;
  name?: string;
  role?: Role;
  phone?: string;
  departmentCode?: string;
}

export interface UpdateUserData {
  matricNO?: string;
  email?: string;
  name?: string;
  role?: Role;
  phone?: string;
  departmentCode?: string;
  isActive?: boolean;
}

export interface QueryParams {
  page?: number;
  limit?: number;
  orderBy?: string;
  orderDirection?: "asc" | "desc";
}

export interface UserFilterParams extends QueryParams {
  role?: Role;
  departmentCode?: string;
  isActive?: boolean;
}

export interface CourseFilterParams extends QueryParams {
  departmentCode?: string;
  level?: Level;
  semester?: Semester;
  isGeneral?: boolean;
  includeGeneral?: boolean;
  searchTerm?: string;
  lecturerId?: string;
  minCredits?: number;
  maxCredits?: number;
}

export interface ScheduleFilterParams extends QueryParams {
  courseCode?: string;
  departmentCode?: string;
  level?: Level;
  semester?: Semester;
  sessionId?: string;
  dayOfWeek?: DayOfWeek;
  sessionType?: SessionType;
  programme?: string;
  startTime?: string;
  endTime?: string;
}

export interface DepartmentFilterParams extends QueryParams {
  searchTerm?: string;
  hasCourses?: boolean;
  withoutCourses?: boolean;
}

export interface ExamFilterParams extends QueryParams {}

export interface LecturerSummary {
  id: string;
  name: string | null;
  email: string;
  departmentCode: string | null;
}

export interface LecturerCourses {
  lecturer: LecturerSummary;
  courses: Course[];
}

export interface LecturerSchedule {
  lecturer: LecturerSummary;
  activeSession: { id: string; name: string } | null;
  schedulesByDay: Record<DayOfWeek, Schedule[]>;
  totalSchedules: number;
}

export interface HealthMemoryStat {
  status: "up" | "down";
  used: number;
  limit: number;
}

export interface HealthCheckResult {
  status: string;
  info: {
    database: { status: string };
    memory_heap: HealthMemoryStat;
    memory_rss: HealthMemoryStat;
  };
  error: Record<string, unknown>;
  details: Record<string, { status: string }>;
}

export interface SimpleHealth {
  status: string;
  timestamp: string;
  uptime: number;
  environment: string;
  version: string;
}

export interface DatabaseHealthTables {
  departments: number;
  courses: number;
  schedules: number;
  users: number;
}

export interface DatabaseHealth {
  status: "ok" | "error";
  database?: {
    connected: boolean;
    responseTime: number;
    tables: DatabaseHealthTables;
  };
  error?: string;
}

export interface ReadinessCheck {
  status: "ready";
  checks: { database: boolean; dependencies: boolean };
}

export interface LivenessCheck {
  status: "alive";
  timestamp: string;
}

export interface AdminDeleteResult {
  deleted: number;
}

export interface AdminDeleteAllResult {
  deleted: Record<string, number>;
}

export interface AdminSeedResult {
  created: number;
  skipped: number;
}

export interface AdminSeedAllResult {
  departments: AdminSeedResult;
  courses: AdminSeedResult;
}
