"use client";

import { Card } from "@/components/ui/card";
import {
  DayOfWeek,
  Level,
  CourseStatistics,
  ScheduleStatistics,
} from "@/types";

const DEPT_BAR_COLORS = [
  "bg-indigo-500",
  "bg-violet-500",
  "bg-sky-500",
  "bg-emerald-500",
  "bg-amber-500",
  "bg-rose-500",
  "bg-pink-500",
  "bg-teal-500",
];

const LEVEL_LABELS: Record<Level, string> = {
  [Level.LEVEL_100]: "100L",
  [Level.LEVEL_200]: "200L",
  [Level.LEVEL_300]: "300L",
  [Level.LEVEL_400]: "400L",
  [Level.LEVEL_500]: "500L",
};

const DAY_CHART_LABELS: Record<DayOfWeek, string> = {
  [DayOfWeek.MONDAY]: "Mon",
  [DayOfWeek.TUESDAY]: "Tue",
  [DayOfWeek.WEDNESDAY]: "Wed",
  [DayOfWeek.THURSDAY]: "Thu",
  [DayOfWeek.FRIDAY]: "Fri",
  [DayOfWeek.SATURDAY]: "Sat",
  [DayOfWeek.SUNDAY]: "Sun",
};

const CHART_DAYS = [
  DayOfWeek.MONDAY,
  DayOfWeek.TUESDAY,
  DayOfWeek.WEDNESDAY,
  DayOfWeek.THURSDAY,
  DayOfWeek.FRIDAY,
];

interface AdminChartsProps {
  courseStats: CourseStatistics | null;
  scheduleStats: ScheduleStatistics | null;
}

export function AdminCharts({ courseStats, scheduleStats }: AdminChartsProps) {
  const totalSchedules = scheduleStats?.totalSchedules ?? 0;
  const autoGenerated = scheduleStats?.autoGenerated ?? 0;
  const manualOverrides = scheduleStats?.manualOverrides ?? 0;

  const deptBreakdown = courseStats?.coursesByDepartment
    ? Object.entries(courseStats.coursesByDepartment)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 8)
    : [];
  const deptMax = deptBreakdown.length
    ? Math.max(1, ...deptBreakdown.map(([, v]) => v))
    : 1;

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <Card className="rounded-xl border p-5">
        <h3 className="font-semibold mb-4">Courses by Level</h3>
        <div className="space-y-3">
          {(Object.values(Level) as Level[]).map((l) => {
            const count = courseStats?.coursesByLevel?.[l] ?? 0;
            const max = Math.max(
              1,
              ...Object.values(courseStats?.coursesByLevel ?? {}),
            );
            const pct = max ? (count / max) * 100 : 0;
            return (
              <div key={l} className="flex items-center gap-3">
                <span className="w-10 text-sm text-gray-600">
                  {LEVEL_LABELS[l]}
                </span>
                <div className="flex-1 h-6 bg-gray-100 rounded overflow-hidden">
                  <div
                    className="h-full bg-indigo-500 rounded transition-all"
                    style={{ width: `${pct}%` }}
                  />
                </div>
                <span className="w-8 text-sm font-medium text-right">
                  {count}
                </span>
              </div>
            );
          })}
        </div>
      </Card>

      <Card className="rounded-xl border p-5">
        <h3 className="font-semibold mb-4">Schedules by Day</h3>
        <div className="flex items-end justify-between gap-2 h-28">
          {CHART_DAYS.map((d) => {
            const count = scheduleStats?.schedulesByDay?.[d] ?? 0;
            const vals = Object.values(
              scheduleStats?.schedulesByDay ?? {},
            ).filter((v): v is number => typeof v === "number");
            const max = Math.max(1, ...vals);
            const heightPct = max ? (count / max) * 100 : 0;
            return (
              <div
                key={d}
                className="flex-1 flex flex-col items-center justify-end gap-1"
              >
                <span className="text-xs text-gray-500">{count}</span>
                <div
                  className="w-full bg-gray-100 rounded-t overflow-hidden"
                  style={{ height: 80 }}
                >
                  <div
                    className="w-full bg-violet-500 rounded-t transition-all"
                    style={{
                      height: `${heightPct}%`,
                      minHeight: count ? 4 : 0,
                    }}
                  />
                </div>
                <span className="text-xs font-medium text-gray-600">
                  {DAY_CHART_LABELS[d]}
                </span>
              </div>
            );
          })}
        </div>
        {totalSchedules > 0 && (
          <div className="flex items-center gap-4 mt-4 pt-4 border-t border-gray-100">
            <div className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-violet-500 shrink-0" />
              <span className="text-xs text-gray-500">
                {autoGenerated} auto-generated
              </span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-full bg-amber-400 shrink-0" />
              <span className="text-xs text-gray-500">
                {manualOverrides} manual override
                {manualOverrides !== 1 ? "s" : ""}
              </span>
            </div>
          </div>
        )}
      </Card>

      <Card className="rounded-xl border p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold">Courses by Department</h3>
          {courseStats?.averageCredits != null && (
            <span className="text-xs text-gray-500 bg-gray-100 px-2.5 py-1 rounded-full">
              Avg {courseStats.averageCredits.toFixed(1)} credits
            </span>
          )}
        </div>
        {deptBreakdown.length === 0 ? (
          <p className="text-sm text-gray-400 italic">No data</p>
        ) : (
          <div className="space-y-3">
            {deptBreakdown.map(([code, count], idx) => {
              const pct = (count / deptMax) * 100;
              return (
                <div key={code} className="flex items-center gap-3">
                  <span className="w-12 text-xs font-mono text-gray-600 shrink-0 truncate">
                    {code}
                  </span>
                  <div className="flex-1 h-6 bg-gray-100 rounded overflow-hidden">
                    <div
                      className={`h-full rounded transition-all ${
                        DEPT_BAR_COLORS[idx % DEPT_BAR_COLORS.length]
                      }`}
                      style={{ width: `${pct}%` }}
                    />
                  </div>
                  <span className="w-8 text-sm font-medium text-right shrink-0">
                    {count}
                  </span>
                </div>
              );
            })}
            {Object.keys(courseStats?.coursesByDepartment ?? {}).length > 8 && (
              <p className="text-xs text-gray-400 pt-1">
                Showing top 8 of{" "}
                {Object.keys(courseStats!.coursesByDepartment).length}{" "}
                departments
              </p>
            )}
          </div>
        )}
      </Card>
    </div>
  );
}
