"use client";

import { useState } from "react";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  BookOpen,
  MessageCircle,
  Building2,
  Clock,
  CalendarDays,
  RefreshCw,
} from "lucide-react";
import {
  AcademicSession,
  CourseStatistics,
  DepartmentStatistics,
  ScheduleStatistics,
} from "@/types";
import { StatCard } from "./stat-card";
import { AdminCharts } from "./admin-charts";
import { GenerateScheduleModal } from "./generate-schedule-modal";

interface AdminDashboardProps {
  deptStats: DepartmentStatistics | null;
  courseStats: CourseStatistics | null;
  scheduleStats: ScheduleStatistics | null;
  activeSession: AcademicSession | null;
  pendingCount: number;
  onRefresh: () => void;
}

export function AdminDashboard({
  deptStats,
  courseStats,
  scheduleStats,
  activeSession,
  pendingCount,
  onRefresh,
}: AdminDashboardProps) {
  const [generateModalOpen, setGenerateModalOpen] = useState(false);

  const totalSchedules = scheduleStats?.totalSchedules ?? 0;
  const autoGenerated = scheduleStats?.autoGenerated ?? 0;
  const manualOverrides = scheduleStats?.manualOverrides ?? 0;
  const schedulesSublabel =
    totalSchedules > 0
      ? `${autoGenerated} auto · ${manualOverrides} manual`
      : undefined;

  return (
    <>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <StatCard
          icon={Building2}
          value={deptStats?.totalDepartments ?? 0}
          label="Total Departments"
          iconBg="bg-indigo-500"
        />
        <StatCard
          icon={BookOpen}
          value={courseStats?.totalCourses ?? 0}
          label="Total Courses"
          iconBg="bg-violet-500"
        />
        <StatCard
          icon={Clock}
          value={totalSchedules}
          label="Total Schedules"
          iconBg="bg-sky-500"
          sublabel={schedulesSublabel}
        />
        <StatCard
          icon={CalendarDays}
          value={activeSession?.name ?? "None"}
          label="Active Session"
          iconBg="bg-emerald-500"
        />
      </div>

      <AdminCharts courseStats={courseStats} scheduleStats={scheduleStats} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="rounded-xl border border-gray-200 p-5">
          <div className="w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center mb-3">
            <RefreshCw className="h-5 w-5 text-white" />
          </div>
          <h3 className="text-base font-semibold mb-2">Generate Schedules</h3>
          <p className="text-[13px] text-gray-500 mb-4">
            Auto-generate timetables for the active session
          </p>
          <Button
            onClick={() => setGenerateModalOpen(true)}
            className="bg-indigo-600 hover:bg-indigo-700 text-white"
          >
            Generate
          </Button>
        </Card>

        <Card className="rounded-xl border border-gray-200 p-5">
          <div className="w-10 h-10 rounded-full bg-amber-500 flex items-center justify-center mb-3">
            <MessageCircle className="h-5 w-5 text-white" />
          </div>
          <h3 className="text-base font-semibold mb-2">Pending Complaints</h3>
          <p className="text-[13px] text-gray-500 mb-2">
            Complaints awaiting your response
          </p>
          <p className="text-4xl font-bold text-amber-600 mb-4">
            {pendingCount}
          </p>
          <Button asChild variant="outline">
            <Link href="/complaints">View Complaints</Link>
          </Button>
        </Card>
      </div>

      <Card className="rounded-xl border border-gray-200 p-5">
        <div className="w-10 h-10 rounded-full bg-emerald-500 flex items-center justify-center mb-3">
          <CalendarDays className="h-5 w-5 text-white" />
        </div>
        <h3 className="text-base font-semibold mb-2">Academic Session</h3>
        <p className="text-[13px] text-gray-500 mb-4">
          {activeSession?.name ?? "None"}
        </p>
        <Button asChild variant="outline">
          <Link href="/sessions">Manage Sessions</Link>
        </Button>
      </Card>

      <GenerateScheduleModal
        open={generateModalOpen}
        onOpenChange={setGenerateModalOpen}
        onSuccess={onRefresh}
      />
    </>
  );
}
